### PR TITLE
SPOI-10712 Add 3.7.1 features to dtmanage page

### PR DESCRIPTION
**Pull request by amberarrow**
Added new feature descriptions and screenshots to dtmanage page.
@sanjaypujare @sandeshh Please review

### CODE REVIEW

**Comment by lizygeogy** [comment]
@sanjaypujare  @sandeshh 
Please check and let me know if these needs to be merged. There is a conflict which needs to be corrected.

**Comment by sanjaypujare** [comment]
@lizygeogy I would say this needs to be merged. But you will need to clean up the PR (now that @amberarrow  is not there) and match the description and screenshots against the latest version (3.10.0). Once that is done @ankitdto can review the PR and merge

**Comment by wvary** [comment]
@sanjaypujare @lizygeogy I'll create a new PR to replace this.  This has some old contents which we don't want to have anymore.

**Comment by sanjaypujare** [comment]
sounds good. Also your new PR will be based off of the latest files so no need to rebase etc...

**Pull request closed without merging**
