### PR TITLE
Adding operator development reference document

### PR DESCRIPTION
**Pull request by bhupeshchawda**

### CODE REVIEW

**Comment by sashadt** [comment]
Several comments on the current MD conversion:

1.  Review for content duplication with current Operator Guide: http://docs.datatorrent.com/operator_development/.  For example, if we already provided introduction to operators, there is no need to do it again in the second guide.  This should cover material not covered in the other guide, and be complimentary, not overlapping.

2.  Remove all the heading table of contents links which are not needed and are currently broken.

3.  There is a list formatted as code which should be fixed.

4.  Provide links to sample code in sample code section.

**Comment by bhupeshchawda** [comment]
Hi Sasha, 
Here are my replies:
1. Operator Development guide is a very basic introduction to operators. Even though (very few) topics seem to be overlapping (like ports), they are very different in the depth of discussion that foes into the two documents. The current pull request targets a reference guide which should be a complete reference on all operator related topics.
2. Removed links in table of contents
3. Fixed formatting for the list
4. Added the link to samples project in Malhar.

**Comment by sandeshh** [comment]
Looks good Bhupesh.

Few comments

CheckpointListener is deprecated

Do we encourage or discourage Activate/Deactivate ( diagram in the following link doesnt contain them http://docs.datatorrent.com/operator_development/ )

Is this going to Apex site ?

**Comment by bhupeshchawda** [comment]
Hi Sandesh
I'll update CheckpointListener to CheckpointNotificationListener.
Also, I think as this is a reference document, we must include activate/deactivate. The operator_development document is more of a basic document on getting people started on operator dev. I did not include it there since this is an advanced concept. 

I think it makes sense to push it to Apex site. @sashadt should I direct this to dt-site?

**Comment by sashadt** [comment]
Yes, @bhupeshchawda, I think this should be targeted for Apex core docs.  

Let's remove TOC to make it consistent also.

**Pull request merged**
