### PR TITLE
Services documentation

### PR DESCRIPTION
**Pull request by wvary**
Added documentation for services.

### CODE REVIEW

**Comment by jessicawangdt** [comment]
confused about what it means:
=========================================================
It saves the services that were added to the system for management, and the settings required to install and launch the services.

**Comment by jessicawangdt** [comment]
The statement has some problem:

"The following services are required by the premium applications in DT RTS:
Online Analytics Service - (blah blah blah)
Drools Workbench -  (blah blah blah)
Superset -  (blah blah blah)"

**Comment by wvary** [comment]
Latest commit addressed three comments by Jessica.

**Comment by jessicawangdt** [comment]
A comma is missing between application ID and application name:

"This section shows the Apex applications that depend on this service. The table will show the application ID application name, application status and the application running username. Users can click on the application ID or name to navigate to the running Apex application instance page."

**Comment by wvary** [comment]
Added comma to address Jessica's latest comment.

**Comment by lizygeogy** [comment]
@wvary I understand, the steps of how Services can be managed in a configuration package will be going into the Creating Application Configuration section. Please confirm.

**Comment by wvary** [comment]
@lizygeogy Yes, we'll document the available actions in the Application Configuration page including some Services actions.  We should refer users to this document for more details so the other documentation doesn't have to explain the fields.

**Comment by jessicawangdt** [comment]
"During the DT RTS installation, the Docker version is automatically detected. That Docker version is shown in the Docker section on the Configuration page."

Maybe we can replace the last two words "Configuration page" with "Configuration step"?

Because when I was reading it initially, I thought "Configuration page" refers to: 
screen shot 2018-02-15 at 11 28 40 am

Then, I realized it refers to the 2nd step in Installation Wizard.

**Comment by sanjaypujare** [comment]
Not sure "configuration step" will solve the issue. May be we can say "RTS configuration"?

 In general in our environment we have generic words like configuration, services, packages which have multiple specific meanings and I don't know how to address that issue. As an example I have been diligent about using the term "DT services" for the new DT services feature we have introduced in 3.10.

**Comment by wvary** [comment]
Latest commit handled Jessica and Sanjay's comments.

**Pull request merged**
