### PR TITLE
HDHT documentation.

### PR DESCRIPTION
**Pull request by tushargosavi**

### CODE REVIEW

**Comment by amberarrow** [comment]
This is much needed documentation and nicely done.

**Comment by tweise** [comment]
Needs to be integrated into left nav.

**Comment by sashadt** [comment]
I will add it to nav when the doc is ready to be merged.  It's needs to go under operators section in mkdocs.yml

**Comment by tushargosavi** [comment]
@amberarrow I have updated the doc. Few sections are expanded based on the review comments.

**Comment by amberarrow** [comment]
Ok, great, I'll review the new revision over the weekend.

**Comment by tushargosavi** [comment]
@amberarrow I have handled the comments.

**Pull request merged**
