### PR TITLE
SPOI-12393 Deleting references of App Data Tracker

### PR DESCRIPTION
**Pull request by lizygeogy**
Removing the complete section of APP Data Tracker.

### CODE REVIEW

**Comment by lizygeogy** [comment]
@rohmurthy please review and merge the edits.

**Comment by lizygeogy** [comment]
@sandeshh, Please review the changes and merge the PR.

**Comment by sandeshh** [comment]
We also need to remove *system app/apps* terminology from the docs, as ADT was the system app and now there is no other app.

**Comment by lizygeogy** [comment]
@sandeshh 
Updated dtmanage file to remove the reference of system app. The other references of System App are from the App Data Tracker chapter, which is deleted from the index, and from the release notes. 
The release notes references are maintained. 

@rohmurthy

**Pull request merged**
