### PR TITLE
Autometrics

### PR DESCRIPTION
**Pull request by davidyan74**

### CODE REVIEW

**Comment by 243826** [comment]
Please have someone do a grammar check on this.

**Comment by sashadt** [comment]
Not a bad idea for all of our docs in general.  Any specific sentences stand out in this one?

**Comment by sashadt** [comment]
image

**Comment by PramodSSImmaneni** [comment]
Just brilliant

**Comment by 243826** [comment]
I did not go through the entire thing but the first paragraph has some
awkward uses of "which".

**Pull request merged**
