### PR TITLE
SPOI-10330 Add documentation for HDFS S3 Sync Application.

### PR DESCRIPTION
**Pull request by deepak-narkhede**
Walkthrough doc for HDFS S3 Sync App.

### CODE REVIEW

**Comment by deepak-narkhede** [comment]
@yogidevendra. Please review

**Comment by yogidevendra** [comment]
@deepak-narkhede Could you please resolve the conflicts?

**Comment by deepak-narkhede** [comment]
@yogidevendra . Conflicts are resolved.

**Comment by yogidevendra** [comment]
This document should be pushed only after corresponding app-template is fixed.

**Pull request merged**
