### PR TITLE
SPOI-11226 Document REST API changes for 3.8 release

### PR DESCRIPTION
**Pull request by sgolovko**
Updated description of the following REST APIs:

POST /ws/v2/licenses
GET /ws/v2/licenses/current

Added description of the following REST APIs:

PUT /ws/v2/systemAlerts/templates/system/"{name}"
DELETE /ws/v2/systemAlerts/templates/system/'{name}"
GET /ws/v2/systemAlerts/templates/system
GET /ws/v2/systemAlerts/templates/system/"{name}"
PUT /ws/v2/systemAlerts/"validate/script"

@wvary @sashadt Could you please review the API description updates
@wvary Could you please add the template structure to the doc?

### CODE REVIEW

**Comment by sgolovko** [comment]
@sashadt @wvary We need to finish documentation of the updates in REST API. Please add your part of the updates.

**Comment by sanjaypujare** [comment]
@wvary @sashadt  are you going to add your content to this PR? Can one of you also review and merge the PR?

**Comment by wvary** [comment]
@sanjaypujare I've created a PR against @sgolovko branch.  He should merge his branch which will update the PR.

**Comment by sanjaypujare** [comment]
@wvary  okay, Can you review this one and give your okay to merge?

**Comment by sgolovko** [comment]
@sanjaypujare The doc updates that include Willet's and my changes are ready to be merged.

**Pull request merged**
