### PR TITLE
Delete app_data_tracker.md

### PR DESCRIPTION
**Pull request by jaysingbahirat**
As per discussion with Mohit, "App Data Tracker" is to be removed from Docs repository.

### CODE REVIEW

**Comment by sashadt** [comment]
@jaysingbahirat There are many other references to App Data Tracker in other docs.  Please go through, identify them, and delete and remove all references along with this change.

**Comment by sashadt** [comment]
@jaysingbahirat Also, which SPOI is this work being done under?

**Comment by jaysingbahirat** [comment]
ADT-11 is the task created to delete ADT references in which all links are mentioned.

**Comment by jaysingbahirat** [comment]
As per latest mail thread we are supporting ADT till 3.9, we will include "Note" in respective links mentioning 'depreciation of ADT' and support till 3.9

**Comment by rohmurthy** [comment]
@sashadt  SPOI-11611 is what Jaysing is currently working on.

**Comment by jaysingbahirat** [comment]
Duplicate of SPOI-12593

**Pull request closed without merging**
