### PR TITLE
Application package & Application configuration package

### PR DESCRIPTION
**Pull request by sandeshh**

### CODE REVIEW

**Comment by tweise** [comment]
Shouldn't this be updated to reflect 3.2? Also there are several places where we should refer to Apache Apex instead of just Apex.

**Comment by sandeshh** [comment]
I just concentrated on the formatting rather than the content.

**Comment by sashadt** [comment]
I believe @davidyan74 needs to review this content.

**Comment by davidyan74** [comment]
I can make updates to this content after sandesh's PR has been merged.

**Comment by sashadt** [comment]
@davidyan74 The content has been merged.  Please update the required content items.

**Pull request merged**
