### PR TITLE
SPOI-12668-Change AppHub to AppFactory

### PR DESCRIPTION
**Pull request by lizygeogy**
@rohmurthy please review.

### CODE REVIEW

**Comment by rohmurthy** [comment]
@lizygeogy - did you also test out the steps on the website and console ?

**Comment by lizygeogy** [comment]
@rohmurthy, I made the text changes to all the references of AppHub in all the commits in this branch except the last two i.e. 
2b87445 and  6ca5660. Those two were changed for images that showed AppHub, but please do not approve them.


--

**Comment by rohmurthy** [comment]
@lizygeogy ones you have all the updates for AppHub changes in place, I will go ahead and review and commit

**Comment by lizygeogy** [comment]
@rohmurthy All the changes are completed for this defect. Please review the updates.

**Pull request merged**
