### PR TITLE
Tutorial for AbstractFileOutputOperator

### PR DESCRIPTION
**Pull request by chandnisingh**
This is turning out to be quite long. Please review

### CODE REVIEW

**Comment by chandnisingh** [comment]
@PramodSSImmaneni

**Comment by sashadt** [comment]
Looks good from my end.  Let me know if I can merge it.

**Comment by amberarrow** [comment]
I'll look at it tomorrow

**Comment by sashadt** [comment]
Any updates on this?  Can I merge it?

**Comment by amberarrow** [comment]
Reviewing it right now.

**Comment by chandnisingh** [comment]
@amberarrow @sashadt @PramodSSImmaneni 

Please merge

**Comment by amberarrow** [comment]
Still reviewing, will likely spill into the weekend.

**Comment by amberarrow** [comment]
Make a couple more suggestions; @sashadt can merge after they are addressed.
Rest looks good.

**Comment by chandnisingh** [comment]
@sashadt @PramodSSImmaneni @amberarrow 
Please merge. Any more additions/changes can be made to this document after this is merged.

**Pull request merged**
