### PR TITLE
Artifacts documentation

### PR DESCRIPTION
**Pull request by wvary**

### CODE REVIEW

**Comment by jessicawangdt** [comment]
maybe append 

" if configuration dt.gateway.maven.local.repo is set in dt-site.xml."
 
to

"JAR files can be uploaded manually and synchronized automatically from a Maven artifacts directory accessible by the Gateway "

?

**Comment by wvary** [comment]
Latest commit handled Jessica's comment.  Although I'm leaving out the dt.gateway.m2home property for now.  I will confirm with Sanjay in the morning.

**Comment by jessicawangdt** [comment]
maybe change

"If you enter the Group ID, Artifact ID and Version that match an existing schema or JAR artifact, you must change one of the fields in order to create the new schema."

to

"If you enter the Group ID, Artifact ID and Version that match an existing schema or JAR artifact, you will see an error 'Artifact groupId: xxx, artifactId: xxx, version: xxx already exists.' and save button will be disabled 
until you change Group ID, Artifact ID or Version"

?

**Comment by wvary** [comment]
Latest commit handled Jessica's comment about existing artifact.

**Comment by wvary** [comment]
@sanjaypujare Let's talk about the dt.gateway.m2home property tomorrow.  On the surface, it doesn't seem why this property is required for synchronization...thanks.

**Comment by ambarishpande** [comment]
@sanjaypujare   ```dt.gateway.m2home``` is the location of your maven binary. For RTS the default location is ```/home/user/datatorrent/current/bin/maven/bin/``` . Whereas the the one you are talking about is ```dt.gateway.m2repo``` which is by default ```/home/user/.dt/.m2/repository``` .  These two properties are necessary for maven configuration and not required for sync. 

Synchronization is done between ```dt.gateway.maven.local.repo``` and hdfs location ```/user/dtadmin/datatorrent/artifacts```  So this property is a required property for sync.

**Comment by wvary** [comment]
@lizygeogy Jessica can see the images fine.  Did you restart mkdocs after you pull my PR?

**Comment by sanjaypujare** [comment]
@ambarishpande  I was indeed talking about the m2 binary directory (I realize "maven home directory" is ambiguous) and not the repo directory. Anyway it looks like @wvary and @jessicawangdt  got all their questions answered

**Pull request merged**
