### PR TITLE
SPOI-12593

### PR DESCRIPTION
**Pull request by jaysingbahirat**
Including "Supporting of 3rd party log aggregations documentation" in the docs.datatorrent.com

### CODE REVIEW

**Comment by lizygeogy** [comment]
Only for testing purposes.

**Comment by lizygeogy** [comment]
@ashwinchandrap @sashadt  @rohmurthy  

Posting this on behalf of Jaysing. 
Please review and approve this PR for addition of this section **"Supporting of 3rd party log aggregations"** which is included in **docs.datatorrent.com** at the following location in the TOC:
**Deployment and Operations** > **Configurations** > **Application** **Configuration**> **Adjusting** **Logging** **Levels**.
 
Reference SPOI-12593

**Comment by lizygeogy** [comment]
@rohmurthy Please reivew and close this item. 
This PR is raise for addition of this section "Supporting of 3rd party log aggregations" which is now included in docs.datatorrent.com at the following location in the TOC:
Deployment and Operations > Configurations > Application Configuration> Adjusting Logging Levels.

**Comment by sandeshh** [comment]
@lizygeogy ADT removal should be done in separate jira, SPOI-12393. Also please make sure that all the references to ADT in http://docs.datatorrent.com/ are edited to reflect the change.

Also it is preferable if the commits are squashed.

**Comment by lizygeogy** [comment]
this is already done in another PR and closed.

**Pull request closed without merging**
